### ISSUE TITLE
[Feature] Use slim docker images instead.

### ISSUE THREAD

**Issue by desteves** [pinecone-io/aws-reference-architecture-pulumi#57]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

This feature aims to greatly reduce the overall time it takes to bring up all the infrastructure resources by adopting `slim` Docker images. I propose we update the `Dockerfiles` containing `FROM node:20.0.0` to instead use `FROM node:20.0.0-slim`

### Describe alternatives you've considered

While we could reduce the image size even further using other tags like `alpine`, these typically require a lot more testing and code changes.

### Who will this benefit?

Anyone deploying the reference architecture.

### Are you interested in contributing this feature?

Sure

### Anything else?

A quick ad-hoc test run resulted in a ~10-minute overall reduction by using slim images.

**Comment by zackproser** [comment]
Thanks - and totally agree. Meant to file this one myself!

**Comment by zackproser** [comment]
Sorry didn't mean to close.

**Comment by desteves** [comment]
https://github.com/pinecone-io/aws-reference-architecture-pulumi/pull/59

**Comment by zackproser** [comment]
I merged #59 so we could call this one good and optionally open another ticket to track figuring out what is up with the semantic-search-postgres Dockerfile later.

Thanks again for the PR!

**Comment by desteves** [comment]
Thanks, Zach! 

Yup, I noticed the semantic search was in an older version but I didn't want to mess with it til I understand it better.
