### ISSUE TITLE
[Bug] The primary architecture diagram is very difficult to understand.

### ISSUE THREAD

**Issue by kirby-jobber** [pinecone-io/aws-reference-architecture-pulumi#63]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The architecture diagram is nearly useless.

It's perfectly reasonable in terms of content and arrangement, but it's unreadable because it is rendered isometrically instead of the standard 2D view.

![arch](https://github.com/pinecone-io/aws-reference-architecture-pulumi/raw/main/docs/aws-ref-arch-pulumi.png)

### Expected Behavior

I want to be able to read the architecture diagram.

For example, here's the same image with a scrappy shear transformation and crop in GIMP:

![rotated](https://github.com/pinecone-io/aws-reference-architecture-pulumi/assets/137355350/ba826d1d-5c37-4764-ba18-e62c841314df)

### Steps To Reproduce

Look at the architecture diagram.

**Comment by aaronkao** [comment]
We may want to just use the 2D flat arch icons that AWS uses now https://aws.amazon.com/architecture/icons/
