### ISSUE TITLE
[Feature] Switch to Pinecone Native Provider

### ISSUE THREAD

**Issue by aaronkao** [pinecone-io/aws-reference-architecture-pulumi#64]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

Once the Pinecone Native Provider is done, we should remove the direct API call from the Pelican microservice to create the index and add the Pinecone index creation in the Pulumi program. 

### Describe alternatives you've considered

This allows Pinecone index creation to be managed in IaC

### Who will this benefit?

All users

### Anything else?

https://github.com/usrbinkat/pulumi-pinecone-native

**Comment by zackproser** [comment]
May close #71
